Repository Solvro/backend-eventownik-v2-legacy, pull requests merged in 2025-03, with the labels that each got.

#156 Feat/add textarea
  app/controllers/events_controller.ts
  app/validators/attribute.ts
Labels: size/S

#163 fix: cascade delete participant_attributes on participant delete
  database/migrations/1741025109483_alter_participant_attribute_cascade_deletes_table.ts
Labels: size/M

#166 Revert "refactor: fix lint warnings"
  app/controllers/forms_controller.ts
Labels: size/XS

#168 fix(ci): use lockfile for building & ignore local node_modules
  .dockerignore
  Dockerfile
Labels: size/S

#170 feat: add migration with show in list to true
  database/migrations/1741355167147_alter_default_show_in_table_attribute_true.ts
Labels: size/S

#172 feat: add location field to event
  app/models/event.ts
  app/validators/event.ts
  database/migrations/1742589668912_add_location_to_events_table.ts
Labels: size/S

#169 feat: add event slug min length validation
  app/validators/event.ts
Labels: size/S

#179 fix: make attribute slug unique to a specific event
  app/controllers/attributes_controller.ts
  app/validators/attribute.ts
  database/migrations/1742475780310_alter_make_attribute_slug_unique_to_one_events_table.ts
Labels: size/M

#183 feat: return created at
  app/controllers/participants_controller.ts
Labels: size/XS

#184 Fix/return created at
  app/controllers/participants_controller.ts
Labels: size/XS

#190 fix: participant attributes
  app/services/participant_service.ts
Labels: size/XS

#191 feat: forms attributes $extras serializer
  app/models/attribute.ts
  app/models/form.ts
Labels: size/S

#193 fix: don't count itself on attribute update slug uniqe
  app/controllers/attributes_controller.ts
  app/validators/attribute.ts
Labels: size/XS

#194 fix: add multiselect to validation on attribute create
  app/validators/attribute.ts
Labels: size/XS

#195 fix: event slug updtate
  app/controllers/events_controller.ts
  app/validators/event.ts
Labels: size/S

#196 refactor: snake case to cammel case
  app/models/form.ts
Labels: size/XS

#197 fix: return admin distinct events
  app/models/admin.ts
Labels: size/XS

#198 fix: remove organizer only from one event
  app/controllers/organizers_controller.ts
  app/services/organizer_service.ts
Labels: size/S

#201 refactor: remove pivot from columns name
  app/models/form.ts
Labels: size/XS

#203 fix: show participant created at field
  app/controllers/participants_controller.ts
Labels: size/XS

#205 feat: add participnat slug dynamic variable in email
  app/services/email_service.ts
Labels: size/XS

#206 fix: isMultipart is optional field
  app/controllers/forms_controller.ts
Labels: size/XS

#210 fix: disable email spoofing
  app/services/email_service.ts
Labels: size/XS

#211 fix: change emails update validator
  app/validators/emails.ts
Labels: size/XS

#213 fix: fix participant created date
  app/controllers/participants_controller.ts
Labels: size/XS

#214 fix: lint warnings
  app/controllers/forms_controller.ts
  app/controllers/participants_controller.ts
Labels: size/S
