Repository Solvro/backend-eventownik-v2-legacy, pull requests merged in 2025-04, with the labels that each got.

#221 feat: use sendLater queue in emails
  app/services/email_service.ts
Labels: size/XS

#225 fix: replace editor images endocing with proper html
  app/services/email_service.ts
Labels: size/XS

#227 fix: attach images as cid
  app/services/email_service.ts
Labels: size/S

#222 refactor: participant-show zwraca wszystkie atrybuty
  app/controllers/participants_controller.ts
Labels: size/XS

#243 refactor: change participant_attributes table value column type to text
  database/migrations/1745499054802_alter_increase_participant_attribute_value_lengths_table.ts
Labels: size/S

#249 feat: attach attributes to participant
  app/controllers/public_participants_controller.ts
  app/models/attribute.ts
  swagger.json
  swagger.yml
Labels: size/XXL

#250 fix: updating block attribute
  app/services/attribute_service.ts
Labels: size/XS

#253 feat: add uploads to persistent storage
  Dockerfile
Labels: size/XS

#254 feat: nullable attribute value
  app/services/email_service.ts
  app/services/participant_service.ts
  app/validators/participants.ts
Labels: size/S

#255 feat: zero means unlimited block capacity
  app/services/block_service.ts
Labels: size/XS

#256 fix: nullable attribute value validation
  app/services/form_service.ts
Labels: size/XS

#257 fix: reverse logic statement
  app/services/block_service.ts
Labels: size/XS

#258 fix: attribute nullable value handling
  app/services/form_service.ts
Labels: size/S

#219 feat/return only selected participants
  app/controllers/event_export_controller.ts
  storage/temp/worksheet.xlsx
Labels: size/S

#261 feat: dont require all fields in update
  app/services/form_service.ts
Labels: size/M

#262 fix: ambiguous id
  app/services/form_service.ts
Labels: size/XS

#263 fix: make options nullable in attribute validator
  app/validators/attribute.ts
Labels: size/XS

#265 refactor: sort blocks by creation date
  app/services/block_service.ts
Labels: size/XS
